import { describe, it, expect, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  createGitHooksPlugin,
  installHook,
  uninstallHook,
} from '../../../src/plugins/optional/git-hooks.js';

describe('Git Hooks Plugin', () => {
  it('should have correct name', () => {
    const plugin = createGitHooksPlugin();
    expect(plugin.name).toBe('git-hooks');
  });

  it('should have correct version', () => {
    const plugin = createGitHooksPlugin();
    expect(plugin.version).toBe('1.0.0');
  });

  it('should have an install method', () => {
    const plugin = createGitHooksPlugin();
    expect(typeof plugin.install).toBe('function');
  });

  it('install should not throw', () => {
    const plugin = createGitHooksPlugin();
    expect(() => plugin.install({} as any)).not.toThrow();
  });

  it('should return a valid plugin object', () => {
    const plugin = createGitHooksPlugin();
    expect(plugin).toHaveProperty('name');
    expect(plugin).toHaveProperty('version');
    expect(plugin).toHaveProperty('install');
  });

  describe('installHook', () => {
    let tempDir: string;

    afterEach(() => {
      if (tempDir) {
        rmSync(tempDir, { recursive: true, force: true });
      }
    });

    it('should return false for a non-git directory', () => {
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-githook-'));
      const result = installHook(tempDir);
      expect(result).toBe(false);
    });

    it('should install hook in a directory with .git folder', () => {
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-githook-'));
      mkdirSync(join(tempDir, '.git'), { recursive: true });

      // installHook calls isGitRepo which does a git rev-parse,
      // so it will fail for a fake .git dir (not a real git repo).
      // This is expected behavior.
      const result = installHook(tempDir);
      // isGitRepo will return false for a fake .git directory
      expect(typeof result).toBe('boolean');
    });

    it('should return false for non-existent directory', () => {
      const result = installHook('/non/existent/path/xyz');
      expect(result).toBe(false);
    });

    it('should install hook in a real git repo', () => {
      const { execFileSync } = require('node:child_process');
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-githook-real-'));
      try {
        execFileSync('git', ['init'], { cwd: tempDir, stdio: 'pipe' });
      } catch {
        // git not available, skip
        return;
      }
      const result = installHook(tempDir);
      expect(result).toBe(true);

      const hookPath = join(tempDir, '.git', 'hooks', 'pre-commit');
      expect(existsSync(hookPath)).toBe(true);
      const content = readFileSync(hookPath, 'utf-8');
      expect(content).toContain('@oxog/codemap');
    });
  });

  describe('uninstallHook', () => {
    let tempDir: string;

    afterEach(() => {
      if (tempDir) {
        rmSync(tempDir, { recursive: true, force: true });
      }
    });

    it('should return true when hook file does not exist', () => {
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-unhook-'));
      mkdirSync(join(tempDir, '.git', 'hooks'), { recursive: true });

      const result = uninstallHook(tempDir);
      expect(result).toBe(true);
    });

    it('should return true when hook exists but has no codemap content', () => {
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-unhook-'));
      mkdirSync(join(tempDir, '.git', 'hooks'), { recursive: true });
      writeFileSync(
        join(tempDir, '.git', 'hooks', 'pre-commit'),
        '#!/bin/sh\necho "other"\n',
      );

      const result = uninstallHook(tempDir);
      expect(result).toBe(true);
    });

    it('should remove codemap hook content', () => {
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-unhook-'));
      mkdirSync(join(tempDir, '.git', 'hooks'), { recursive: true });
      const hookPath = join(tempDir, '.git', 'hooks', 'pre-commit');
      writeFileSync(
        hookPath,
        '#!/bin/sh\n# Auto-generated by @oxog/codemap\nnpx @oxog/codemap\ngit add .codemap/map.txt\n',
      );

      const result = uninstallHook(tempDir);
      expect(result).toBe(true);
      // Hook file should be deleted since only codemap content was there
      expect(existsSync(hookPath)).toBe(false);
    });

    it('should preserve other hook content when removing codemap', () => {
      tempDir = mkdtempSync(join(tmpdir(), 'codemap-test-unhook-'));
      mkdirSync(join(tempDir, '.git', 'hooks'), { recursive: true });
      const hookPath = join(tempDir, '.git', 'hooks', 'pre-commit');
      writeFileSync(
        hookPath,
        '#!/bin/sh\neslint .\n# Auto-generated by @oxog/codemap\nnpx @oxog/codemap\ngit add .codemap/map.txt\n',
      );

      const result = uninstallHook(tempDir);
      expect(result).toBe(true);
      expect(existsSync(hookPath)).toBe(true);

      const content = readFileSync(hookPath, 'utf-8');
      expect(content).toContain('eslint');
      expect(content).not.toContain('npx @oxog/codemap');
    });
  });
});
