// Install/uninstall a git pre-commit hook that auto-regenerates the codemap
//
// The hook runs `npx codemap` before each commit to keep the map in sync.
import { existsSync, writeFileSync, unlinkSync, chmodSync } from 'node:fs';
import { join } from 'node:path';

const HOOK_PATH = join('.git', 'hooks', 'pre-commit');

const HOOK_CONTENT = `#!/bin/sh
# Auto-generated by @oxog/codemap
# Regenerate codemap before each commit
npx codemap
git add .codemap/
`;

function install(): void {
  if (!existsSync('.git')) {
    console.error('Not a git repository. Run "git init" first.');
    process.exit(1);
  }

  writeFileSync(HOOK_PATH, HOOK_CONTENT);
  chmodSync(HOOK_PATH, '755');
  console.log('Pre-commit hook installed at', HOOK_PATH);
}

function uninstall(): void {
  if (existsSync(HOOK_PATH)) {
    unlinkSync(HOOK_PATH);
    console.log('Pre-commit hook removed');
  } else {
    console.log('No hook found at', HOOK_PATH);
  }
}

// Usage: npx tsx setup.ts install | uninstall
const action = process.argv[2];
if (action === 'install') install();
else if (action === 'uninstall') uninstall();
else console.log('Usage: npx tsx setup.ts [install|uninstall]');
