/**
 * Git operations for incremental scanning and hook management.
 *
 * Uses child_process.execFileSync to safely interact with git CLI.
 * @module
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync, unlinkSync, chmodSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Safely run a git command using execFileSync (no shell injection risk).
 */
function gitExec(args: string[], cwd?: string): string {
  return execFileSync('git', args, {
    cwd,
    stdio: 'pipe',
    encoding: 'utf-8',
  }).trim();
}

/**
 * Check if git is available in the current environment.
 *
 * @returns True if `git --version` succeeds
 */
export function isGitAvailable(): boolean {
  try {
    gitExec(['--version']);
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if the given directory is inside a git repository.
 *
 * @param dir - Directory to check
 * @returns True if directory is in a git repo
 */
export function isGitRepo(dir: string): boolean {
  try {
    gitExec(['rev-parse', '--is-inside-work-tree'], dir);
    return true;
  } catch {
    return false;
  }
}

/**
 * Get the root of the git repository containing the given directory.
 *
 * @param dir - Directory to check
 * @returns Absolute path to git root, or null
 */
export function getGitRoot(dir: string): string | null {
  try {
    return gitExec(['rev-parse', '--show-toplevel'], dir);
  } catch {
    return null;
  }
}

/**
 * Get list of files changed since the last commit (or since a given ref).
 *
 * @param dir - Repository directory
 * @param ref - Git ref to compare against (default: HEAD)
 * @returns Array of changed file paths (relative to repo root)
 */
export function getChangedFiles(dir: string, ref: string = 'HEAD'): string[] {
  try {
    const files = new Set<string>();

    // Get unstaged changes
    const diffOutput = gitExec(['diff', '--name-only', ref], dir);

    // Get staged changes
    const stagedOutput = gitExec(['diff', '--cached', '--name-only'], dir);

    // Get untracked files
    const untrackedOutput = gitExec(
      ['ls-files', '--others', '--exclude-standard'],
      dir,
    );

    for (const output of [diffOutput, stagedOutput, untrackedOutput]) {
      if (output) {
        for (const line of output.split('\n')) {
          const trimmed = line.trim();
          if (trimmed) {
            files.add(trimmed);
          }
        }
      }
    }

    return [...files];
  } catch {
    return [];
  }
}

/**
 * Compute a simple hash of file content for cache comparison.
 * Uses a fast string hash (djb2 algorithm).
 *
 * @param content - File content to hash
 * @returns Hash string
 */
export function hashContent(content: string): string {
  let hash = 5381;
  for (let i = 0; i < content.length; i++) {
    hash = ((hash << 5) + hash + (content.charCodeAt(i) ?? 0)) | 0;
  }
  return (hash >>> 0).toString(36);
}

/**
 * Install a git pre-commit hook that runs codemap.
 *
 * @param repoDir - Root of the git repository
 * @returns True if hook was installed successfully
 */
export function installPreCommitHook(repoDir: string): boolean {
  const hooksDir = join(repoDir, '.git', 'hooks');
  const hookPath = join(hooksDir, 'pre-commit');

  if (!existsSync(join(repoDir, '.git'))) {
    return false;
  }

  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  const hookContent = `#!/bin/sh
# Auto-generated by @oxog/codemap
# Regenerate codemap before commit

npx @oxog/codemap
git add .codemap/map.txt
`;

  if (existsSync(hookPath)) {
    const existing = readFileSync(hookPath, 'utf-8');
    if (existing.includes('@oxog/codemap')) {
      return true;
    }
    writeFileSync(hookPath, existing + '\n' + hookContent);
  } else {
    writeFileSync(hookPath, hookContent);
  }

  try {
    chmodSync(hookPath, 0o755);
  } catch {
    // chmod may fail on Windows
  }

  return true;
}

/**
 * Uninstall the codemap pre-commit hook.
 *
 * @param repoDir - Root of the git repository
 * @returns True if hook was removed successfully
 */
export function uninstallPreCommitHook(repoDir: string): boolean {
  const hookPath = join(repoDir, '.git', 'hooks', 'pre-commit');

  if (!existsSync(hookPath)) {
    return true;
  }

  const content = readFileSync(hookPath, 'utf-8');

  if (!content.includes('@oxog/codemap')) {
    return true;
  }

  const lines = content.split('\n');
  const otherLines = lines.filter(
    (line) =>
      !line.includes('@oxog/codemap') &&
      !line.includes('npx @oxog/codemap') &&
      !line.includes('git add .codemap/map.txt') &&
      line.trim() !== '' &&
      !line.startsWith('#!/bin/sh') &&
      !line.startsWith('# Auto-generated by'),
  );

  if (otherLines.length === 0) {
    unlinkSync(hookPath);
  } else {
    writeFileSync(hookPath, '#!/bin/sh\n' + otherLines.join('\n') + '\n');
  }

  return true;
}
